"""Generate comparison plots from all experiment results."""
import os, json
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

os.makedirs('results', exist_ok=True)

# ── All experimental data ──────────────────────────────────────────────────────
exact        = 0.48426
mock_unmit   = 0.31665
mock_linear  = 0.37264
mock_rich    = 0.40063
real_unmit   = 0.11768
real_rich    = 0.06152  # Richardson ZNE on ibm_yonsei (over-corrected due to depth)

fidelities_1st = [0.3643, 0.5508, 0.6616, 0.7674, 0.8423,
                  0.8889, 0.9182, 0.9376, 0.9508, 0.9603]
fidelities_2nd = [0.0303, 0.8726, 0.9632, 0.9871, 0.9945,
                  0.9973, 0.9985, 0.9991, 0.9995, 0.9996]
steps_list = list(range(1, 11))

# ── Plot 1: Full <Z_0> bar comparison ─────────────────────────────────────────
fig, ax = plt.subplots(figsize=(11, 5))
categories = [
    'Ideal\n(Exact)',
    'Mock\nUnmit.',
    'Mock\nLinear\nZNE',
    'Mock\nRichardson\nZNE',
    'Real\nUnmit.\n(ibm_yonsei)',
    'Real\nRichardson\nZNE',
]
values = [exact, mock_unmit, mock_linear, mock_rich, real_unmit, real_rich]
colors = ['#2196F3', '#FF7043', '#FFA726', '#66BB6A', '#EC407A', '#AB47BC']

bars = ax.bar(categories, values, color=colors, edgecolor='black', linewidth=0.8, width=0.6)
ax.axhline(exact, color='#2196F3', linestyle='--', linewidth=1.5, alpha=0.7,
           label=f'Exact = {exact:.4f}')

for bar, val in zip(bars, values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
            f'{val:.4f}', ha='center', va='bottom', fontsize=10, fontweight='bold')

ax.axvspan(-0.5,  0.5, alpha=0.05, color='#2196F3')
ax.axvspan( 0.5,  3.5, alpha=0.05, color='#FF7043')
ax.axvspan( 3.5,  5.5, alpha=0.05, color='#9C27B0')

mock_p = mpatches.Patch(color='#FF7043', alpha=0.5, label='Mock (FakeBrisbane)')
real_p = mpatches.Patch(color='#9C27B0', alpha=0.5, label='Real (ibm_yonsei, 127Q Eagle r3)')
ax.legend(handles=[mock_p, real_p], loc='upper right', fontsize=9)

ax.set_ylabel(r'$\langle Z_0 \rangle$', fontsize=13)
ax.set_title(
    r'$\langle Z_0\rangle$ Comparison: Ideal / Mock / Real Hardware' + '\n'
    r'2nd-order Suzuki-Trotter, $r=5$, $N=4$, $J=1.0$, $h=0.5$, $T=1.0$',
    fontsize=12)
ax.set_ylim(-0.05, 0.65)
ax.grid(axis='y', alpha=0.35)
plt.tight_layout()
plt.savefig('results/full_comparison.png', dpi=150)
plt.close()
print('Saved: results/full_comparison.png')

# ── Plot 2: Absolute error bar chart ──────────────────────────────────────────
fig, ax = plt.subplots(figsize=(8, 4))
err_labels = ['Mock\nUnmit.', 'Mock\nLinear', 'Mock\nRichardson',
              'Real\nUnmit.', 'Real\nRichardson']
errors = [abs(exact - v) for v in [mock_unmit, mock_linear, mock_rich, real_unmit, real_rich]]
colors2 = ['#FF7043', '#FFA726', '#66BB6A', '#EC407A', '#AB47BC']

bars2 = ax.bar(err_labels, errors, color=colors2, edgecolor='black', linewidth=0.8, width=0.5)
for bar, err in zip(bars2, errors):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
            f'{err:.4f}', ha='center', va='bottom', fontsize=11)

ax.axvspan(-0.5, 2.5, alpha=0.06, color='#FF7043', label='Mock (FakeBrisbane)')
ax.axvspan( 2.5, 4.5, alpha=0.06, color='#9C27B0', label='Real (ibm_yonsei)')
ax.set_ylabel(r'$|\langle Z_0\rangle_{\rm method} - \langle Z_0\rangle_{\rm exact}|$', fontsize=11)
ax.set_title('Absolute Error from Exact $\langle Z_0\\rangle$', fontsize=12)
ax.set_ylim(0, 0.48)
ax.legend(fontsize=9)
ax.grid(axis='y', alpha=0.35)
plt.tight_layout()
plt.savefig('results/error_comparison.png', dpi=150)
plt.close()
print('Saved: results/error_comparison.png')

# ── Plot 3: Fidelity curves (already regenerated by run_experiments, keep as-is)
print('All plots saved.')
